### ISSUE TITLE
Pip install fails (virtualenv python 3.5.2)

### ISSUE THREAD

**Issue by Recmo** [niltonvolpato/python-progressbar#54]
```
(env) $ pip install progressbar
Collecting progressbar
  Using cached progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k88aurgf/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/tmp/pip-build-k88aurgf/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/tmp/pip-build-k88aurgf/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "[…]/env/lib/python3.5/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k88aurgf/progressbar/
```

**Comment by dpdornseifer** [comment]
Same issue for me - virtualenv / python 3.5

**Comment by pixelou** [comment]
same here.

**Comment by danodonovan** [comment]
Possibly related issue https://github.com/niltonvolpato/python-progressbar/issues/28

For what it's worth, [this fork](https://github.com/germangh/python-progressbar) provides python 3 functionality (also 2 compatible) and is also [available on pypi](https://pypi.python.org/pypi/progressbar33)

    $ pip install progressbar33

**Comment by sursh** [comment]
I'm having the same issue, and progressbar33 worked for me. thanks, @danodonovan

**Comment by Thetoxicarcade** [comment]
I might have to use progressbar33 if the install won't work for this one.

**Comment by nicholasli137** [comment]
The following works for me (both Python 2 and 3).
```
pip install progressbar2
```

**Comment by mattpitkin** [comment]
Also

```
pip install progressbar-latest
```

seems to work with at least Python 3.5.2.

**Comment by thecountoftuscany** [comment]
Also facing the exact same problem. Possible solutions I saw on stackoverflow and github were:

1. install or upgrade the `python3-pip`, `setuptools`, `pip`, `python-dev`, libpq-dev`, `ez_setup` packages
2. Use the `--no-cache-dir` flag with `pip`
3. Use differenet versions of `progressbar`, specifically, `progressbar2` or `progressbar33` or `progressbar-latest`
4. Clear the `~/.cache/pip` directory
5. Give the power of `sudo -H` to `pip`
6. Using `pip3` instead of `pip`

None of these have worked so far.
(Python version 2.7.12, python3 version 3.5.2, pip version 10.0.1)

**Comment by toxik-io** [comment]
Ouch.

**Comment by niltonvolpato** [comment]
This issue seems to have been fixed. Can you guys try again, and please let me know if it still doesn't work.
